# To be tested
version: "3.7"
services:
    atlassian-bitbucket:
        container_name: atlassianBitbucketProd

        environment:
        	VIRTUAL_HOST: ${HOST:?Missing environment variable see readme}
            VIRTUAL_PORT: 7990
            LETSENCRYPT_HOST: ${HOST:?Missing environment variable see readme}
            ATL_PROXY_NAME: ${HOST:?Missing environment variable see readme}
            ATL_PROXY_PORT: 443
            ATL_TOMCAT_SECURE: 1
            JDBC_URL: jdbc:postgresql://postgres:5432/${PG_DB-atlassianBitbucketProd}
            JDBC_USER: ${PG_USER-atlassianBitbucketProd}
            JDBC_PASSWORD: ${PG_PASSWORD:?Missing environment variable see readme}
            JDBC_DRIVER: org.postgresql.Driver

            networks:
                - default
                - nginxproxynet

        ports:
            - 7990

    postgres:
        ports:
            - 5432

        container_name: atlassianBitbucketPostgresqlProd

        environment:
            POSTGRES_USER: ${PG_USER-atlassianBitbucketProd}
            POSTGRES_PASSWORD: ${PG_PASSWORD:?Missing environment variable see readme}
            POSTGRES_DB: ${PG_DB-atlassianBitbucketProd}

networks:
    nginxproxynet:
        external: true
